name: Notify Google Apps Script

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV

      - name: Debugging information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Timestamp: ${{ github.event.head_commit.timestamp }}"
          echo "Commit URL: ${{ github.event.head_commit.url }}"

      - name: Send webhook to Google Apps Script
        run: |
          RESPONSE=$(curl -X POST "https://script.google.com/macros/s/AKfycbyVLXPSeDxLlj9U-tbM_m19aiA0ZumnKbRoHKx_hy6JSJQVDn6QR_pIxozAsiz53D0qGg/exec" \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: ${{ secrets.GITHU_WEBHOOK_SECRET }}" \
          -d '{
            "repository": {
              "full_name": "${{ github.repository }}"
            },
            "action": "push",
            "commits": [
              {
                "author": {
                  "name": "${{ github.actor }}"
                },
                "message": "${{ github.event.head_commit.message }}",
                "timestamp": "${{ github.event.head_commit.timestamp }}",
                "url": "${{ github.event.head_commit.url }}"
              }
            ]
          }')
          echo "Response from Google Apps Script: $RESPONSE"
