name: Notify Google Apps Script

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Google Apps Script
        run: |
          curl -X POST "https://script.google.com/macros/s/AKfycbyVLXPSeDxLlj9U-tbM_m19aiA0ZumnKbRoHKx_hy6JSJQVDn6QR_pIxozAsiz53D0qGg/exec" \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: ${{ secrets.GITHU_WEBHOOK_SECRET }}" \
          -d '{
            "repository": {
              "full_name": "${{ github.repository }}"
            },
            "action": "push",
            "commits": [
              {
                "author": {
                  "name": "${{ github.actor }}"
                },
                "message": "${{ github.event.head_commit.message }}",
                "timestamp": "${{ github.event.head_commit.timestamp }}",
                "url": "${{ github.event.head_commit.url }}"
              }
            ]
          }'
